### ISSUE TITLE
Query incrementation

### ISSUE THREAD

**Issue by rsoloff** [raymasaki/supermassive#1]
@jasonseminara @amcooper @zhenpanda @WilliamfShaw 

I am currently working on a trending function that will add all the search queries to the database. If the search query is already in the database, instead of adding the word it should increase their count. The words are added to the database with a parameter of count that starts at 1. I currently can add queries to the database and check if the search is already there to prevent repeats. However I am having trouble getting the count to increment whenever a query that already was present has been hit.

Thank you, Ross

**Comment by WilliamfShaw** [comment]
@rsoloff Has this been addressed?
